- hosts: HAPROXY
  vars_files:
          - variables.yml
  tasks:
       - name: copy configuration file in haproxy/
         template:
                 src: /root/workspace/haproxy.cfg
                 dest: /etc/haproxy/haproxy.cfg
         notify:
                 - Restart haproxy

  handlers:
       - name: Restart haproxy 
         service:
               name: haproxy
               state: restarted
       
