###### Configuration plan for HAPROXY ##################

# 1. check connectivity with managed node
# 2. download HAPROXY and install on one of the managed node
# 3. Configure HAPROXY
     # 3.1.  create HAPROXY config file using jinja language
# 4. install Apache web server on Backend nodes 
    # 4.0  install php on backend server
    # 4.1. put php files in document root
    # 4.2. start web server services 
# 5. start the HAPROXY services

#########################################################

- hosts: HAPROXY
  tasks: 
       - name: install HAPROXY 
         dnf:
             name: haproxy.x86_64
             state: latest
         register: msg

       - name: Getting status of HAPROXY
         debug:
              var: msg 