####### configuration plan for dynamic variable files according to OS name #########
## 1. init roles
## 2. create two variable files named OS_name.yml
## 3. install apache web server
## 4. package name take from above variable files dynamically according to OS name
## 5. start the services

- hosts: all
  vars_files:
         - "{{ansible_facts['distribution']}}.yml"

  tasks:
         - name: install apache webserver
           yum:
                name: "{{ package }}"
                state: latest

         - name: Add Rules in Firewalls of web servers
           ansible.posix.firewalld:
                               port: "{{ web_port }}/tcp"
                               permanent: yes
                               state: enabled
                               immediate: yes     

         - name: Start Web server service
           service:
                  name: httpd
                  state: started
                  enabled: yes
             
