- hosts: MasterNode
  tasks:
        - name : Format MasterNode
          shell:
               cmd: echo Y | hadoop namenode -format

        - name : Run MasterNode
          shell:
               cmd: hadoop-daemon.sh start namenode
          register: msg

        - name: Check status
          shell:
               cmd: jps
          register: status

        - name: Getting initlization msg
          debug:
              var: msg

        - name: Getting MasterNode Status
          debug:
              var: status

