####### configuration plan for dynamic variable files according to OS name #########
## 1. create two variable files named OS_name.yml
## 2. install apache web server
## 3. package name take from above variable files dynamically according to OS name
## 4. start the services

- hosts: all
  vars_files:
         - "{{ansible_facts['distribution']}}.yml"

  tasks:
         - name: install apache webserver
           package:
                name: "{{ package }}"
                state: latest    

         - name: Start Web server service
           service:
                  name: "{{ package }}"
                  state: started
                  
             
